from yacs.config import CfgNode as CN
def get_cfg():
  cfg=CN()
  cfg.MODEL=CN()
  cfg.MODEL.MICRONETS=CN()
  cfg.MODEL.ACTIVATION=CN()
  cfg.MODEL.MICRONETS.BLOCK="DYMicroBlock" 
  cfg.MODEL.MICRONETS.NET_CONFIG="msnx_dy12_exp6_20M_020" 
  cfg.MODEL.MICRONETS.STEM_CH=12 
  cfg.MODEL.MICRONETS.STEM_GROUPS=4,3
  cfg.MODEL.MICRONETS.STEM_DILATION=1 
  cfg.MODEL.MICRONETS.STEM_MODE="spatialsepsf" 
  cfg.MODEL.MICRONETS.OUT_CH=1024 
  cfg.MODEL.MICRONETS.DEPTHSEP=True 
  cfg.MODEL.MICRONETS.POINTWISE="group" 
  cfg.MODEL.MICRONETS.DROPOUT=0.1 
  cfg.MODEL.ACTIVATION.MODULE="DYShiftMax" 
  cfg.MODEL.ACTIVATION.ACT_MAX=2.0 
  cfg.MODEL.ACTIVATION.LINEARSE_BIAS=False 
  cfg.MODEL.ACTIVATION.INIT_A_BLOCK3=1.0,0.0 
  cfg.MODEL.ACTIVATION.INIT_A=1.0,0.5 
  cfg.MODEL.ACTIVATION.INIT_B=0.0,0.5 
  cfg.MODEL.ACTIVATION.REDUCTION=8
  cfg.MODEL.MICRONETS.SHUFFLE=True 
  return cfg